catalog/urls.py
from django.urls import path

from .views import (add_video_catalog, export_to_excel, send_to_tg,
                    video_catalog_list)

urlpatterns = [
    # Другие URL-маршруты вашего приложения
    path('', video_catalog_list, name='video_catalog_list'),
    path('add/', add_video_catalog, name='add_video_catalog'),
    path('export_to_excel/', export_to_excel, name='export_to_excel'),
    path('send_to_tg/', send_to_tg, name='send_to_tg'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('user/', include('users.urls', namespace='user'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.logout, name='logout'),
]

catalog/models.py
from django.db import models
from django.utils import timezone, dateformat

from users.models import User


class VideoCatalog(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    created_timestamp = models.DateTimeField(default=dateformat.format(timezone.localtime(timezone.now()), 'Y-m-d H:i'), verbose_name='Дата добавления')
    performer = models.CharField(max_length=30, verbose_name="Исполнитель")
    title = models.CharField(max_length=30, verbose_name="Название")
    duration = models.DurationField(verbose_name="Хронометраж", blank=True, null=True)
    video_type = models.CharField(max_length=30, verbose_name="Тип", blank=True, null=True)
    director = models.CharField(max_length=30, verbose_name="Режиссёр", blank=True, null=True)
    screenwriter = models.CharField(max_length=30, verbose_name="Сценарист", blank=True, null=True)
    composer = models.CharField(max_length=30, verbose_name="Композитор", blank=True, null=True)
    year = models.PositiveIntegerField(verbose_name="Год", blank=True, null=True)
    youtube_link = models.URLField(verbose_name="Youtube", blank=True, null=True)
    rutube_link = models.URLField(verbose_name="RuTube", blank=True, null=True)
    yandex_link = models.URLField(verbose_name="Яндекс", blank=True, null=True)
    vk_link = models.URLField(verbose_name="VK", blank=True, null=True)
    zen_link = models.URLField(verbose_name="Дзен", blank=True, null=True)
    upc = models.CharField(max_length=30, verbose_name="UPC", blank=True, null=True)
    files = models.FileField(blank=True, null=True, verbose_name='Файлы')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Видеокаталог"
        verbose_name_plural = "Видеокаталоги"

    def display_id(self):
        return f'{self.id:04}'

catalog/forms.py
from django import forms
from django.utils import dateformat
from django.utils.timezone import localtime, now

from .models import VideoCatalog


class VideoCatalogForm(forms.ModelForm):
    class Meta:
        model = VideoCatalog
        fields = [
            'user',
            'created_timestamp',
            'performer',
            'title',
            'duration',
            'video_type',
            'director',
            'screenwriter',
            'composer',
            'year',
            'youtube_link',
            'rutube_link',
            'yandex_link',
            'vk_link',
            'zen_link',
            'upc',
            'files'
        ]
    created_timestamp = forms.DateTimeField(
        label='Дата добавления',
        widget=forms.TextInput(attrs={'readonly': True,
                                      'value': dateformat.format(localtime(now()), 'Y-m-d H:i'),
                                      'class': 'date-input'})
    )

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()

catalog/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.sites import requests
from django.http import HttpResponse
from django.shortcuts import redirect, render
from openpyxl import Workbook

from .forms import VideoCatalogForm
from .models import VideoCatalog


def video_catalog_list(request):
    video_catalogs = VideoCatalog.objects.all()
    return render(request, 'video_catalog_list.html', {'video_catalogs': video_catalogs})


def add_video_catalog(request):
    if request.method == 'POST':
        form = VideoCatalogForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Запись добавлена")
            return redirect('add_video_catalog')
        else:
            messages.error(request, "Ошибка в форме")
    else:
        form = VideoCatalogForm()

    return render(request, 'add_video_catalog.html', {'form': form})


def export_to_excel(request):
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = 'attachment; filename="video_catalog.xlsx"'
    wb = Workbook()
    ws = wb.active
    headers = ['№ каталога', 'Исполнитель', 'Название', 'Хронометраж', 'Тип', 'Режиссёр', 'Сценарист', 'Композитор',
               'Год', 'Youtube', 'RuTube', 'Яндекс', 'VK', 'Дзен', 'UPC']
    ws.append(headers)
    data = VideoCatalog.objects.all()

    for item in data:
        row = [item.catalog_number, item.performer, item.title, item.duration, item.video_type, item.director,
               item.screenwriter, item.composer, item.year, item.youtube_link, item.rutube_link, item.yandex_link,
               item.vk_link, item.zen_link,
               item.upc]
        ws.append(row)

    wb.save(response)

    return response


def send_to_tg(request):
    data = VideoCatalog.objects.all()
    for item in data:
        message = ''
        message += f'№ каталога: {item.catalog_number}\n'
        message += f'Исполнитель: {item.performer}\n'
        message += f'Название: {item.title}\n'
        message += f'Хронометраж: {item.duration}\n'
        message += f'Тип: {item.video_type}\n'
        message += f'Режиссёр: {item.director}\n'
        message += f'Сценарист: {item.screenwriter}\n'
        message += f'Композитор: {item.composer}\n'
        message += f'Год: {item.year}\n'
        message += 'Youtue: ' + f'[Ссылка]({item.youtube_link})' if item.youtube_link else 'Youtue: -'
        message += '\nRuTube: ' + f'[Ссылка]({item.rutube_link})' if item.rutube_link else '\nRuTube: -'
        message += '\nЯндекс: ' + f'[Ссылка]({item.yandex_link})' if item.yandex_link else '\nЯндекс: -'
        message += '\nVK: ' + f'[Ссылка]({item.vk_link})' if item.vk_link else '\nVK: -'
        message += '\nДзен: ' + f'[Ссылка]({item.zen_link})' if item.zen_link else '\nДзен: -'
        message += f'\nUPC: {item.upc}\n\n'
        if item.files:
            params = {
                'chat_id': settings.TELEGRAM_CHAT_ID,
                'caption': message,
                'parse_mode': 'markdown',
            }
            with open(item.files.path, 'rb') as file:
                files = {'document': (item.files.name, file)}
                response = requests.get(f'https://api.telegram.org/bot{settings.TELEGRAM_API_TOKEN}/sendDocument',
                                        params=params, files=files)
        else:
            params = {
                'chat_id': settings.TELEGRAM_CHAT_ID,
                'text': message,
                'parse_mode': 'markdown'
            }
            response = requests.get(f'https://api.telegram.org/bot{settings.TELEGRAM_API_TOKEN}/sendMessage',
                                    params=params)
        if response.status_code == 200:
            messages.success(request, "Данные отправлены в телеграм")
            print('Сообщение успешно отправлено')
        else:
            messages.error(request, "Ошибка при отправке сообщения:" + response.text)
            print('Ошибка при отправке сообщения:', response.text)
    return redirect('video_catalog_list')

templates/add_video_catalog.html
{% extends "base.html" %} {% load static %} {% block content %}



<div class="content-container">


    <h1 class="h1">Добавить видео в&nbsp;каталог</h1>

    <!--    <a href="{% url 'video_catalog_list' %}">-->
    <!--        <button class="btn btn-primary default-btn">Назад</button>-->
    <!--    </a>-->


    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}


        {{ form.as_p }}

        <button type="submit" class="button">
            Сохранить
        </button>
        <!--            <a-->
        <!--                    href="{% url 'video_catalog_list' %}"-->
        <!--                    class="btn btn-primary default-btn"-->
        <!--            >-->
        <!--                Список-->
        <!--            </a>-->
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Работа с видеокаталогом</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"-->
<!--          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'deps/css/main.css'%}">
</head>
<body>

{% if not user.is_authenticated %}
<div class="user-auth-cont">
    <a href="{% url 'user:login' %}" class="login-btn">Войти</a>
</div>
{% else %}
<div class="user-auth-cont">
    <p class="user-name-txt">{{user.username}}</p>
    <a href="{% url 'user:logout' %}" class="pop-up-logout">Выйти</a>
</div>
{% endif %}

<div class="side-menu">
    <a href="/" class="logo-img">
        <img src="{% static 'deps/img/logo.jpg' %}" alt="logo">
    </a>
    <a href="{% if user.is_authenticated %}{% url 'add_video_catalog' %}{% else %}{% url 'user:login' %}{% endif %}" class="side-menu-link">добавить</a>
    <a href="/" class="side-menu-link">каталог видео</a>
    <a href="{% url 'export_to_excel' %}" class="side-menu-link">выгрузить excel</a>
    <a href="{% url 'send_to_tg' %}" class="side-menu-link">отправить</a>
    <a href="/admin" class="side-menu-link">редактировать</a>
</div>

<div class="side-menu-icon js-menu-icon">
    <img src="{% static 'deps/img/menu.svg' %}" alt="logo">
</div>

{% if messages %}
<div class="modal js-modal">
    <div class="cross js-cross"></div>
    <ul class="messages">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="container">
    {% block content %}
    {% endblock %}

</div>
<script type="text/javascript" src="{% static 'deps/js/script.js' %}""></script>

</body>
</html>

templates/video_catalog_list.html
{% extends "base.html" %} {% load static %} {% block content %}

<div class="content-container wide">

  <h1 class="h1">Каталог видео</h1>


  <div class="search-input-wrapper">
  <input type="text" class="input search-input js-search-input" placeholder="Поиск">
    <div class="search-cross js-search-cross">×</div>
  </div>

  <table class="js-search-table" >
    <thead >
    <tr>
      <th>№ каталога</th>
      <th>Менеджер</th>
      <th>Дата добавления</th>
      <th>Исполнитель</th>
      <th>Название</th>
      <th>Хронометраж</th>
      <th>Тип</th>
      <th>Режиссёр</th>
      <th>Сценарист</th>
      <th>Композитор</th>
      <th>Год</th>
      <th>Youtube</th>
      <th>RuTube</th>
      <th>Яндекс</th>
      <th>VK</th>
      <th>Дзен</th>
      <th>UPC</th>
      <th>Файл</th>
    </tr>
    </thead>
    <tbody>
    {% for item in video_catalogs %}
    <tr>
      <td>vj{{ item.display_id }}</td>
      <td>{{ item.user.username }}</td>
      <td>{{ item.created_timestamp }}</td>
      <td>{{ item.performer }}</td>
      <td>{{ item.title }}</td>
      <td>{{ item.duration }}</td>
      <td>{{ item.video_type }}</td>
      <td>{{ item.director }}</td>
      <td>{{ item.screenwriter }}</td>
      <td>{{ item.composer }}</td>
      <td>{{ item.year }}</td>
      <td>
        <a target="_blank" href="{{ item.youtube_link }}">Ссылка</a>
        {% if item.youtube_link %} {% else %}  {% endif %}
      </td>
      <td>
        {% if item.rutube_link %}
        <a target="_blank" href="{{ item.rutube_link }}">Ссылка</a>
        {% else %} - {% endif %}
      </td>
      <td>
        {% if item.yandex_link %}
        <a target="_blank" href="{{ item.yandex_link }}">Ссылка</a>
        {% else %} - {% endif %}
      </td>
      <td>
        {% if item.vk_link %}
        <a target="_blank" href="{{ item.vk_link }}">Ссылка</a>
        {% else %} - {% endif %}
      </td>
      <td>
        {% if item.zen_link %}
        <a target="_blank" href="{{ item.zen_link }}">Ссылка</a>
        {% else %} - {% endif %}
      </td>
      <td>{{ item.upc }}</td>
      <td>
        {% if item.files %}
        <a href="{{ item.files.url }}">Файл</a>
        {% else %} - {% endif %}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="9">Нет данных.</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

  <script>

    const items = [
    {% for item in video_catalogs %}
    {
      catalogNumber: '{{ item.catalog_number }}',
      performer: '{{ item.performer }}',
      title: '{{ item.title }}',
      duration: '{{ item.duration }}',
      video_type: '{{ item.video_type }}',
      director: '{{ item.director }}',
      screenwriter: '{{ item.screenwriter }}',
      composer: '{{ item.composer }}',
      year: '{{ item.year }}',
      youtube_link: '{% if item.youtube_link %}{{ item.youtube_link }}{% else %}{% endif %}',
      rutube_link: '{% if  item.rutube_link %}{{ item.rutube_link }}{% else %}{% endif %}',
      yandex_link: '{% if  item.yandex_link %}{{ item.yandex_link }}{% else %}{% endif %}',
      vk_link: '{% if  item.vk_link %}{{ item.vk_link }}{% else %}{% endif %}',
      zen_link: '{% if  item.zen_link %}{{ item.zen_link }}{% else %}{% endif %}',
      upc: '{{ item.upc }}',
      files: '{% if  item.files %}{{ item.files.url }}{% else %}{% endif %}',
    },
    {% empty %}
    {% endfor %}
    ]

  </script>

</div>
{% endblock %}

users/templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Джем - Авторизация</title>
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"-->
<!--          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'deps/css/main.css'%}">
</head>
<body>
    <div class="login-box">
        <div class="login-box-content">
            <form class="login-form" action="{% url 'user:login' %}" method="post">
                {% csrf_token %}
                <label class="login-label">Имя пользователя</label>
                <input class="login-input" name="username" type="text" placeholder="Введите имя">
                <label class="login-label">Пароль</label>
                <input class="login-input" name="password" type="password" placeholder="Введите пароль">
                <button type="submit">Войти</button>
            </form>
        </div>
    </div>
</body>
</html>

users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>